# coding: utf-8

"""
    Hotelspro Api Client

    Hotelspro Api Client

    OpenAPI spec version: 2.0.0
    Contact: clientintegration@hotelspro.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import hotelspro_client
from hotelspro_client.rest import ApiException
from hotelspro_client.models.cancel_response import CancelResponse


class TestCancelResponse(unittest.TestCase):
    """ CancelResponse unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCancelResponse(self):
        """
        Test CancelResponse
        """
        # FIXME: construct object with mandatory attributes with example values
        #model = hotelspro_client.models.cancel_response.CancelResponse()
        pass


if __name__ == '__main__':
    unittest.main()
