# coding: utf-8

"""
    Hotelspro Api Client

    Hotelspro Api Client

    OpenAPI spec version: 2.0.0
    Contact: clientintegration@hotelspro.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.apis.default_api import DefaultApi


class TestDefaultApi(unittest.TestCase):
    """ DefaultApi unit test stubs """

    def setUp(self):
        self.api = swagger_client.apis.default_api.DefaultApi()

    def tearDown(self):
        pass

    def test_availability_product_code_get(self):
        """
        Test case for availability_product_code_get

        Availability with Product Code
        """
        pass

    def test_book_provision_code_post(self):
        """
        Test case for book_provision_code_post

        Book with Provision Code
        """
        pass

    def test_bookings_booking_code_get(self):
        """
        Test case for bookings_booking_code_get

        Get Booking Detail
        """
        pass

    def test_bookings_get(self):
        """
        Test case for bookings_get

        Get Booking List
        """
        pass

    def test_cancel_booking_code_post(self):
        """
        Test case for cancel_booking_code_post

        Cancel Booking with Booking Code
        """
        pass

    def test_hotel_availability_get(self):
        """
        Test case for hotel_availability_get

        Hotel Availability with Hotel Code and Search Code
        """
        pass

    def test_provision_product_code_post(self):
        """
        Test case for provision_product_code_post

        Provision with Product Code
        """
        pass

    def test_search_post(self):
        """
        Test case for search_post

        Search with Hotel Code(Hotel Code List) or Destination Code or Geolocation
        """
        pass


if __name__ == '__main__':
    unittest.main()
