# coding: utf-8

"""
    Hotelspro Api Client

    Hotelspro Api Client

    OpenAPI spec version: 2.0.0
    Contact: clientintegration@hotelspro.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.models.provision_response import ProvisionResponse


class TestProvisionResponse(unittest.TestCase):
    """ ProvisionResponse unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testProvisionResponse(self):
        """
        Test ProvisionResponse
        """
        # FIXME: construct object with mandatory attributes with example values
        #model = swagger_client.models.provision_response.ProvisionResponse()
        pass


if __name__ == '__main__':
    unittest.main()
