# coding: utf-8

"""
    Hotelspro Api Client

    Hotelspro Api Client

    OpenAPI spec version: 2.0.0
    Contact: clientintegration@hotelspro.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import hotelspro_client
from hotelspro_client.rest import ApiException
from hotelspro_client.models.booking_list_response import BookingListResponse


class TestBookingListResponse(unittest.TestCase):
    """ BookingListResponse unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testBookingListResponse(self):
        """
        Test BookingListResponse
        """
        # FIXME: construct object with mandatory attributes with example values
        #model = hotelspro_client.models.booking_list_response.BookingListResponse()
        pass


if __name__ == '__main__':
    unittest.main()
