# coding: utf-8

"""
    Hotelspro Api Client

    Hotelspro Api Client

    OpenAPI spec version: 2.0.0
    Contact: clientintegration@hotelspro.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class BookResponseRooms(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """


    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'room_description': 'str',
        'room_type': 'str'
    }

    attribute_map = {
        'room_description': 'room_description',
        'room_type': 'room_type'
    }

    def __init__(self, room_description=None, room_type=None):
        """
        BookResponseRooms - a model defined in Swagger
        """

        self._room_description = None
        self._room_type = None

        if room_description is not None:
          self.room_description = room_description
        if room_type is not None:
          self.room_type = room_type

    @property
    def room_description(self):
        """
        Gets the room_description of this BookResponseRooms.

        :return: The room_description of this BookResponseRooms.
        :rtype: str
        """
        return self._room_description

    @room_description.setter
    def room_description(self, room_description):
        """
        Sets the room_description of this BookResponseRooms.

        :param room_description: The room_description of this BookResponseRooms.
        :type: str
        """

        self._room_description = room_description

    @property
    def room_type(self):
        """
        Gets the room_type of this BookResponseRooms.

        :return: The room_type of this BookResponseRooms.
        :rtype: str
        """
        return self._room_type

    @room_type.setter
    def room_type(self, room_type):
        """
        Sets the room_type of this BookResponseRooms.

        :param room_type: The room_type of this BookResponseRooms.
        :type: str
        """

        self._room_type = room_type

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, BookResponseRooms):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
