# coding: utf-8

"""
    Hotelspro Api Client

    Hotelspro Api Client

    OpenAPI spec version: 2.0.0
    Contact: clientintegration@hotelspro.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class HotelAvailabilityResponse(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """


    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'count': 'int',
        'code': 'str',
        'results': 'list[Product]'
    }

    attribute_map = {
        'count': 'count',
        'code': 'code',
        'results': 'results'
    }

    def __init__(self, count=None, code=None, results=None):
        """
        HotelAvailabilityResponse - a model defined in Swagger
        """

        self._count = None
        self._code = None
        self._results = None

        self.count = count
        self.code = code
        self.results = results

    @property
    def count(self):
        """
        Gets the count of this HotelAvailabilityResponse.
        number of returned hotel

        :return: The count of this HotelAvailabilityResponse.
        :rtype: int
        """
        return self._count

    @count.setter
    def count(self, count):
        """
        Sets the count of this HotelAvailabilityResponse.
        number of returned hotel

        :param count: The count of this HotelAvailabilityResponse.
        :type: int
        """
        if count is None:
            raise ValueError("Invalid value for `count`, must not be `None`")

        self._count = count

    @property
    def code(self):
        """
        Gets the code of this HotelAvailabilityResponse.
        search code

        :return: The code of this HotelAvailabilityResponse.
        :rtype: str
        """
        return self._code

    @code.setter
    def code(self, code):
        """
        Sets the code of this HotelAvailabilityResponse.
        search code

        :param code: The code of this HotelAvailabilityResponse.
        :type: str
        """
        if code is None:
            raise ValueError("Invalid value for `code`, must not be `None`")

        self._code = code

    @property
    def results(self):
        """
        Gets the results of this HotelAvailabilityResponse.

        :return: The results of this HotelAvailabilityResponse.
        :rtype: list[Product]
        """
        return self._results

    @results.setter
    def results(self, results):
        """
        Sets the results of this HotelAvailabilityResponse.

        :param results: The results of this HotelAvailabilityResponse.
        :type: list[Product]
        """
        if results is None:
            raise ValueError("Invalid value for `results`, must not be `None`")

        self._results = results

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, HotelAvailabilityResponse):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
