# coding: utf-8

"""
    Hotelspro Api Client

    Hotelspro Api Client

    OpenAPI spec version: 2.0.0
    Contact: clientintegration@hotelspro.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class Room(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """


    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'pax': 'Pax',
        'room_category': 'str',
        'room_description': 'str',
        'nightly_prices': 'object',
        'room_type': 'str'
    }

    attribute_map = {
        'pax': 'pax',
        'room_category': 'room_category',
        'room_description': 'room_description',
        'nightly_prices': 'nightly_prices',
        'room_type': 'room_type'
    }

    def __init__(self, pax=None, room_category=None, room_description=None, nightly_prices=None, room_type=None):
        """
        Room - a model defined in Swagger
        """

        self._pax = None
        self._room_category = None
        self._room_description = None
        self._nightly_prices = None
        self._room_type = None

        if pax is not None:
          self.pax = pax
        if room_category is not None:
          self.room_category = room_category
        if room_description is not None:
          self.room_description = room_description
        if nightly_prices is not None:
          self.nightly_prices = nightly_prices
        if room_type is not None:
          self.room_type = room_type

    @property
    def pax(self):
        """
        Gets the pax of this Room.

        :return: The pax of this Room.
        :rtype: Pax
        """
        return self._pax

    @pax.setter
    def pax(self, pax):
        """
        Sets the pax of this Room.

        :param pax: The pax of this Room.
        :type: Pax
        """

        self._pax = pax

    @property
    def room_category(self):
        """
        Gets the room_category of this Room.

        :return: The room_category of this Room.
        :rtype: str
        """
        return self._room_category

    @room_category.setter
    def room_category(self, room_category):
        """
        Sets the room_category of this Room.

        :param room_category: The room_category of this Room.
        :type: str
        """

        self._room_category = room_category

    @property
    def room_description(self):
        """
        Gets the room_description of this Room.

        :return: The room_description of this Room.
        :rtype: str
        """
        return self._room_description

    @room_description.setter
    def room_description(self, room_description):
        """
        Sets the room_description of this Room.

        :param room_description: The room_description of this Room.
        :type: str
        """

        self._room_description = room_description

    @property
    def nightly_prices(self):
        """
        Gets the nightly_prices of this Room.

        :return: The nightly_prices of this Room.
        :rtype: object
        """
        return self._nightly_prices

    @nightly_prices.setter
    def nightly_prices(self, nightly_prices):
        """
        Sets the nightly_prices of this Room.

        :param nightly_prices: The nightly_prices of this Room.
        :type: object
        """

        self._nightly_prices = nightly_prices

    @property
    def room_type(self):
        """
        Gets the room_type of this Room.

        :return: The room_type of this Room.
        :rtype: str
        """
        return self._room_type

    @room_type.setter
    def room_type(self, room_type):
        """
        Sets the room_type of this Room.

        :param room_type: The room_type of this Room.
        :type: str
        """

        self._room_type = room_type

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, Room):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
