# coding: utf-8

"""
    Hotelspro Api Client

    Hotelspro Api Client

    OpenAPI spec version: 2.0.0
    Contact: clientintegration@hotelspro.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

# import models into model package
from .availability_response import AvailabilityResponse
from .book_response import BookResponse
from .book_response_confirmation_numbers import BookResponseConfirmationNumbers
from .book_response_hotel_payment_info import BookResponseHotelPaymentInfo
from .book_response_rooms import BookResponseRooms
from .booking_list_response import BookingListResponse
from .cancel_response import CancelResponse
from .error import Error
from .error_details import ErrorDetails
from .hotel_availability_response import HotelAvailabilityResponse
from .pax import Pax
from .policy import Policy
from .product import Product
from .provision_response import ProvisionResponse
from .results import Results
from .room import Room
from .search_response import SearchResponse
