# coding: utf-8

"""
    Hotelspro Api Client

    Hotelspro Api Client

    OpenAPI spec version: 2.0.0
    Contact: clientintegration@hotelspro.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class BookResponseHotelPaymentInfo(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """


    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'hotel_currency': 'str',
        'hotel_price': 'str'
    }

    attribute_map = {
        'hotel_currency': 'hotel_currency',
        'hotel_price': 'hotel_price'
    }

    def __init__(self, hotel_currency=None, hotel_price=None):
        """
        BookResponseHotelPaymentInfo - a model defined in Swagger
        """

        self._hotel_currency = None
        self._hotel_price = None

        if hotel_currency is not None:
          self.hotel_currency = hotel_currency
        if hotel_price is not None:
          self.hotel_price = hotel_price

    @property
    def hotel_currency(self):
        """
        Gets the hotel_currency of this BookResponseHotelPaymentInfo.

        :return: The hotel_currency of this BookResponseHotelPaymentInfo.
        :rtype: str
        """
        return self._hotel_currency

    @hotel_currency.setter
    def hotel_currency(self, hotel_currency):
        """
        Sets the hotel_currency of this BookResponseHotelPaymentInfo.

        :param hotel_currency: The hotel_currency of this BookResponseHotelPaymentInfo.
        :type: str
        """

        self._hotel_currency = hotel_currency

    @property
    def hotel_price(self):
        """
        Gets the hotel_price of this BookResponseHotelPaymentInfo.

        :return: The hotel_price of this BookResponseHotelPaymentInfo.
        :rtype: str
        """
        return self._hotel_price

    @hotel_price.setter
    def hotel_price(self, hotel_price):
        """
        Sets the hotel_price of this BookResponseHotelPaymentInfo.

        :param hotel_price: The hotel_price of this BookResponseHotelPaymentInfo.
        :type: str
        """

        self._hotel_price = hotel_price

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, BookResponseHotelPaymentInfo):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
