# coding: utf-8

"""
    Hotelspro Api Client

    Hotelspro Api Client

    OpenAPI spec version: 2.0.0
    Contact: clientintegration@hotelspro.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class CancelResponse(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """


    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'currency': 'str',
        'charge_amount': 'str',
        'code': 'str'
    }

    attribute_map = {
        'currency': 'currency',
        'charge_amount': 'charge_amount',
        'code': 'code'
    }

    def __init__(self, currency=None, charge_amount=None, code=None):
        """
        CancelResponse - a model defined in Swagger
        """

        self._currency = None
        self._charge_amount = None
        self._code = None

        self.currency = currency
        self.charge_amount = charge_amount
        self.code = code

    @property
    def currency(self):
        """
        Gets the currency of this CancelResponse.

        :return: The currency of this CancelResponse.
        :rtype: str
        """
        return self._currency

    @currency.setter
    def currency(self, currency):
        """
        Sets the currency of this CancelResponse.

        :param currency: The currency of this CancelResponse.
        :type: str
        """
        if currency is None:
            raise ValueError("Invalid value for `currency`, must not be `None`")
        allowed_values = ["USD", "EUR", "GBP", "TRY", "AED"]
        if currency not in allowed_values:
            raise ValueError(
                "Invalid value for `currency` ({0}), must be one of {1}"
                .format(currency, allowed_values)
            )

        self._currency = currency

    @property
    def charge_amount(self):
        """
        Gets the charge_amount of this CancelResponse.

        :return: The charge_amount of this CancelResponse.
        :rtype: str
        """
        return self._charge_amount

    @charge_amount.setter
    def charge_amount(self, charge_amount):
        """
        Sets the charge_amount of this CancelResponse.

        :param charge_amount: The charge_amount of this CancelResponse.
        :type: str
        """
        if charge_amount is None:
            raise ValueError("Invalid value for `charge_amount`, must not be `None`")

        self._charge_amount = charge_amount

    @property
    def code(self):
        """
        Gets the code of this CancelResponse.

        :return: The code of this CancelResponse.
        :rtype: str
        """
        return self._code

    @code.setter
    def code(self, code):
        """
        Sets the code of this CancelResponse.

        :param code: The code of this CancelResponse.
        :type: str
        """
        if code is None:
            raise ValueError("Invalid value for `code`, must not be `None`")

        self._code = code

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, CancelResponse):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
